/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function sort(input: string): string

export interface SortOptions {
  pretty: boolean
  sortScripts: boolean
}

export declare function sortWithOptions(input: string, options: SortOptions): string
