/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Options for controlling JSON formatting when sorting */
export interface SortOptions {
  /** Whether to pretty-print the output JSON */
  pretty: boolean
  /** Whether to sort the scripts field alphabetically */
  sortScripts: boolean
}

/** Sorts a package.json string with default options (pretty-printed) */
export declare function sortPackageJson(input: string): string

/** Sorts a package.json string with custom options */
export declare function sortPackageJsonWithOptions(input: string, options: SortOptions): string
